version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrosystem-app
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - agrosystem

  db:
    image: postgres:15
    container_name: agrosystem-db
    environment:
      POSTGRES_DB: agrosystem
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - agrosystem

  nginx:
    image: nginx:alpine
    container_name: agrosystem-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - agrosystem

networks:
  agrosystem:
    driver: bridge

volumes:
  dbdata: